import type { ReactNode } from 'react'

export const emptyLine = <div style={{ opacity: "0", userSelect: "none" }}>{"awa"}</div>

export const shellMsgs: ReactNode[] = [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ Command // 奇妙打指令的地方 ]"}</>,
  emptyLine,
  <>{"Version // 0.3.0"}</>,
  emptyLine,
  <>{"這個就是一個很智障的東西 難用死 拓展性差"}</>,
  <>{"但真的很好玩 就....特別好玩"}</>,
  <>{"反正 寫這個東西的目的 就是 帥 就這樣 沒了"}</>,
  emptyLine,
  <>{"小故事 : "}</>,
  <>{"之所以叫 \"奇妙打指令的地方\" 是因爲之前"}</>,
  <>{"在AD還有管理員的時候 他在我伺服器建了一個用機器人的頻道"}</>,
  <>{"頻道名稱就真的叫做 \"奇妙打指令的地方\""}</>,
  <>{"後來寫了這個東西 在想中文名要叫啥 然後 想到這個東西 就這樣叫了"}</>,
  emptyLine,
  <>{"#####################################"}</>,
]

export const projectMsgs = (ver: string): ReactNode[] => [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ Project KILO ]"}</>,
  emptyLine,
  <>{"Version // " + ver}</>,
  emptyLine,
  <>{"一個放自己所有作品的地方 可以算是一個大雜燴"}</>,
  <>{"這個東西會伴隨我一生直到我死去"}</>,
  <>{"然後永遠不會公開 公開就不禮貌了"}</>,
  <>{"反正....就這樣"}</>,
  emptyLine,
  <>{"#####################################"}</>,
]

export const fontUseMsgs: ReactNode[] = [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ 字體的使用 ]"}</>,
  emptyLine,
  <>{"# "}<a href='https://store.justfont.com/' target='_blank'>{"JustFont"}</a>{" - "}<a href='https://justfont.com/huninn/' target='_blank'>{"OpenHuninn 2.1"}</a></>,
  <>{"一個十分好的這個 很圓的字體"}</>,
  <>{"目前所有的排版都是針對這個字體下去設計的"}</>,
  <>{"所以換了字體 我的網頁就會直接炸掉"}</>,
  emptyLine,
  <>{"OpenHuninn : "}<a href='https://justfont.com/huninn/' target='_blank'>{"https://justfont.com/huninn/"}</a></>,
  <>{"JustFont : "}<a href='https://store.justfont.com/' target='_blank'>{"https://store.justfont.com/"}</a></>,
  emptyLine,
  <>{"# "}<a href='https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip' target='_blank'>{"Hack Nerd Font"}</a></>,
  <>{"給終端 程式碼用的"}</>,
  <>{"會直接替代monospace 啊 十分的好"}</>,
  <>{"所以你在那些 額 什麽鳥地方看到的那些 帶圖示的字符"}</>,
  <>{"在這個終端裏面 理論上來講 應該都是可以用的"}</>,
  emptyLine,
  <>{"Nerd Fonts : "}<a href='https://www.nerdfonts.com/' target='_blank'>{"https://www.nerdfonts.com/"}</a></>,
  emptyLine,
  <>{"# "}<a href='https://github.com/ButTaiwan/genseki-font/' target='_blank'>{"Genseki Font"}</a></>,
  <>{"一個相對沒那麽圓的 標準字體 我比較喜歡"}</>,
  <>{"個人在某些正式的地方 會用到這個字體 很棒"}</>,
  emptyLine,
  <>{"Genseki Font : "}<a href='https://github.com/ButTaiwan/genseki-font/' target='_blank'>{"https://github.com/ButTaiwan/genseki-font/"}</a></>,
  emptyLine,
  <>{"# "}<a href='https://github.com/ButTaiwan/genryu-font/' target='_blank'>{"Genryu Font"}</a></>,
  <>{"寫一點 文藝的東西的時候 會不錯"}</>,
  <>{"反正 欸 還挺好"}</>,
  emptyLine,
  <>{"Genryu Font : "}<a href='https://github.com/ButTaiwan/genryu-font/' target='_blank'>{"https://github.com/ButTaiwan/genryu-font/"}</a></>,
  emptyLine,
  <>{"#####################################"}</>,
]

export const iconUseMsgs: ReactNode[] = [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ 圖示的使用 ]"}</>,
  emptyLine,
  <>{"# "}<a href='https://fonts.google.com/icons' target='_blank'>{"Google.Font"}</a></>,
  <>{"大部分常見的圖示都是這裏抓來的"}</>,
  emptyLine,
  <>{"Font.Google : "}<a href='https://fonts.google.com/icons' target='_blank'>{"https://fonts.google.com/icons"}</a></>,
  emptyLine,
  <>{"# "}<a href='https://icons8.com/' target='_blank'>{"Icons8"}</a></>,
  <>{"然後像是應用程式的圖示啊 之類的 啊 隨便啦"}</>,
  emptyLine,
  <>{"Icons8 : "}<a href='https://icons8.com/' target='_blank'>{"https://icons8.com/"}</a></>,
  emptyLine,
  <>{"#####################################"}</>,
]

export const musicMsgs: ReactNode[] = [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ 音樂和音效 ]"}</>,
  emptyLine,
  <>{"音樂我寫的"}</>,
  <>{"音效也是"}</>,
  <>{"拜托看一下我 "}<a href='https://open.spotify.com/artist/1MCtBV218RV96NvuvOtPEN' target='_blank'>{"spotify"}</a>{" 和 "}<a href='https://music.youtube.com/channel/UCI9Fxq7m3MupJPziIzFJqCg' target='_blank'>{"youtube music"}</a></>,
  <>{"額 雖然 好像....好對不起 好像沒什麽好看的算了"}</>,
  <>{"反正 這邊先甩兩個連結"}</>,
  emptyLine,
  <>{"spotify : "}<a href='https://open.spotify.com/artist/1MCtBV218RV96NvuvOtPEN' target='_blank'>{"https://open.spotify.com/artist/1MCtBV218RV96NvuvOtPEN"}</a></>,
  <>{"youtube music : "}<a href='https://music.youtube.com/channel/UCI9Fxq7m3MupJPziIzFJqCg' target='_blank'>{"https://music.youtube.com/channel/UCI9Fxq7m3MupJPziIzFJqCg"}</a></>,
  emptyLine,
  <>{"#####################################"}</>,
]

export const kiloMsgs: ReactNode[] = [
  <>{"#####################################"}</>,
  emptyLine,
  <>{"[ KIASENOLO / KILO / KIASE ]"}</>,
  emptyLine,
  <>{""}</>,
  emptyLine,
  <>{"#####################################"}</>,
]
